added width adjustment input box to Editor Preferences menu
lmg-anon/mikupad pull request #24
Opened 2024-01-21 18:07 UTC by infinitelydense

Recreated [PR 19](https://github.com/lmg-anon/mikupad/pull/19) from a separate branch. Hopefully it looks good this time, please let me know if anything else needs fixing.

2024-01-21 18:55 UTC, lmg-anon requested changes

2024-01-21 18:55 UTC, lmg-anon commented on mikupad.html
> +
Is there a reason to use `:root` instead of the `html` one below?

2024-01-21 18:55 UTC, lmg-anon commented on mikupad.html
>  @media (min-width: calc(40.5em + 250px)) {
You also need to change this media rule and the one above, this should be the code that you need to use:
```css
@media (min-width: calc(calc(var(--prompt-container-width) * 1.125rem) + 250px))
```

2024-01-21 23:12 UTC, closed without merging

2024-01-21 23:31 UTC, infinitelydense commented
No reason it couldn't be in the html instead of root, that would be better. When it came to updating the media rule, using the prompt-container-width variable as described caused the sidebar to attach incorrectly. 

I think this project is awesome, but judging from my accidental closing of this request, I think I'll need to learn how to use git a bit better before contributing. 😅 I'll just leave this closed to avoid any further inconvenience.

2024-01-22 15:20 UTC, lmg-anon commented
Don`t worry, it's not an inconvenience. Contributions are always welcome, and I can see why this is a useful feature.
When you feel comfortable to continue, feel free to reopen the PR.