Feature/instruct templates
lmg-anon/mikupad pull request #56
Opened 2024-05-01 19:53 UTC by neCo2

I've added functionality to select from a list of instruct formats. Then you can either click a button to insert the template directly into your prompt, or you can use placeholders, `{sys}` `{/sys}` `{inst}` and `{/inst}` in your prompt instead, which will be replaced with the selected instruct formats when being evaluated by the model.
You can also add, delete, import and export templates. The UI's ugly as sin, so I'll be more than happy to implement any suggestions you can think of.
![firefox_2024-05-01_21-37-11](https://github.com/lmg-anon/mikupad/assets/50079394/c3e7262f-99c9-44ae-990e-70d5bd427d9d)
![firefox_2024-05-01_19-49-38](https://github.com/lmg-anon/mikupad/assets/50079394/8cd3d8a8-5431-4ad7-b572-89a43918a988)
![firefox_2024-05-01_20-19-06](https://github.com/lmg-anon/mikupad/assets/50079394/22d5dbe1-4455-4326-bfc8-15c0d9667466)

I've never worked with indexedDB before, so be sure to double check the code related to this. Judging by some situations I've seen early on, this has potential to lock up the entire page if the db version upgrade doesn't work as intended, until you either clear the storage, or downgrade mikupad.

2024-05-01 19:54 UTC, neCo2 commented on mikupad.html
> +				${(options = typeof options === 'function' ? options() : options).map(o => html`<option
Made this able to evaluate expressions. Didn't end up using it here, but I thought I might as well leave it in.

2024-05-07 17:34 UTC, neCo2 commented
Having used this for a week now, I'm not sure whether the selected session should be persistent or tied to session. Currently, it's persistent. What do you think?

2024-05-19 02:19 UTC, lmg-anon commented
Sorry for my lateness, but this looks VERY solid!

>Having used this for a week now, I'm not sure whether the selected template should be persistent or tied to session. Currently, it's persistent. What do you think?

In my opinion, it makes complete sense for the templates to be persistent. In fact, being tied to the session is an issue with how World Info works right now.

Anyway, I'm not very good with UIs either, but here are some of my thoughts for improvements:

- These icons look quite out of place, they are often associated with "Command Prompt" and "information," respectively. However, I think your idea of using icons was good, and I have no clue what else could fit better... So I guess it's okay to keep these icons if no one gets a better idea.
![image](https://github.com/lmg-anon/mikupad/assets/139719567/2d3108b5-2d4c-4be3-be96-fefc0a35ad8e)

- This button should probably be called "Re-Set Defaults" or "Re-Add Defaults".
![image](https://github.com/lmg-anon/mikupad/assets/139719567/9b35e846-7ac4-461c-9e04-cdd4c201b8b5)

- It's a bit unclear what the "Import"/"Export" buttons actually do because they are on the same line as the currently selected template (Also, the Export button tooltip is wrong). I think it would be better to show a clear separation, like below:
![image](https://github.com/lmg-anon/mikupad/assets/139719567/6fa3af4a-4ff6-4389-b3e7-5039676fdca4)

- Creating a new prompt template isn't very obvious because the name change only reflects after you re-open the modal.
![image](https://github.com/lmg-anon/mikupad/assets/139719567/51a31dbc-f2bb-4e56-b09a-4b78e1f9ad5d)

2024-05-19 08:50 UTC, neCo2 commented
Put the import/export stuff on a separate line and fixed the name and tooltip.

> they are often associated with "Command Prompt" and "information," respectively

I know, but it's the best I could come up with apart from just an "S" and "I".

> name change only reflects after you re-open the modal

Frankly, I can't figure out how to get the name to live-update without breaking stuff.
I made it so that it makes an entry named "New Template" now instead of a completely blank entry. Maybe that helps a little.

2024-05-19 12:35 UTC, neCo2 commented
Added a chat mode similar to what #61 implemented, but working with the instruct templates. You can click the indicated Icon to switch between Completion and Chat mode.
![firefox_2024-05-19_14-30-05](https://github.com/lmg-anon/mikupad/assets/50079394/bf2cb50c-19cc-4390-94b6-5e9810eaf3e3)

2024-05-19 19:00 UTC, lmg-anon commented
>Frankly, I can't figure out how to get the name to live-update without breaking stuff.
I made it so that it makes an entry named "New Template" now instead of a completely blank entry. Maybe that helps a little.

Yes, that is better, but I think you could implement live-updating like this. I just tested it here and it seems to work fine:
- Add a new state to keep track of the new name (`const [newTemplateName, setNewTemplateName] = useState(undefined);`)
- Update the state in `handleInstructTemplateChange` together with `nameNew`
- Undefine the state in `updateTemplateDB`
- Set the `value` in `SelectBoxTemplate` to be `newTemplateName ?? selectedTemplate` instead of `selectedTemplate`
- Change the code in `SelectBoxTemplate` to use `o.nameNew` instead of `o.value`/`o.name`

>Just to be clear, I meant the selectedTemplate variable, not the actual templates object.

Oh yeah, `selectedTemplate` makes sense to be tied to the session, just like everything else in the "Parameters" group.

>Also what's the issue with world info being bound to sessions? I guess it's not ideal when you have an entry you want to use in multiple sessions, but could be mostly mitigated with import/export functions, which are probably way overdue anyways.

Yes, it's just to be able to easily share with other sessions and avoid duplication of data. One could have a list of different World Infos, and easily switch between them. But I agree, import/export functions would mitigate this nicely.

>Added a chat mode similar to what https://github.com/lmg-anon/mikupad/pull/61 implemented, but working with the instruct templates. You can click the indicated Icon to switch between Completion and Chat mode. Again unsure whether chat mode should be persistent or session-based.

This works pretty nicely, damn. I think this could also be tied to the session.

2024-05-19 19:49 UTC, neCo2 commented
That works great! Added the live-updating just like you suggested, and tied `selectedTemplate` and `chatMode` to session.
And now that the title's live-updating, I also changed back to a fully empty entry for adding a new template.

>One could have a list of different World Infos, and easily switch between them

That's a great idea. It should be possible to copy a lot of the code of this PR to save and update WI to the indexedDB. Maybe I'll look into that.

2024-05-19 20:07 UTC, lmg-anon requested changes

2024-05-19 20:07 UTC, lmg-anon commented on mikupad.html
> +	const updateTemplateDBCaller = useMemo(() => {
same as `updateTemplateList`

2024-05-19 20:52 UTC, neCo2 commented on mikupad.html
> +		this.templates = {};
I'd really appreciate if you could handle that. I've got no clue about how indexedDB actually works or what the best practices are.
And I'll see about the rest of the changes tomorrow.

2024-05-20 08:29 UTC, neCo2 commented on mikupad.html
> +	const updateTemplateList = useMemo(() => {
I suppose I'll have to read up on the exact differences between them.

2024-05-20 08:37 UTC, neCo2 commented on mikupad.html
> +	// re-selecting doesn't work properly when I move this inside the InstructModal
If I recall correctly, there were some issues when adding a new template related to `selectedTemplate`, but it appears to be working correctly now. Maybe the fix for the live name updating also fixed this?

2024-05-20 08:43 UTC, neCo2 commented
Changed the indicated useMemos to useEffect and moved `updateTemplateList` inside the instruct modal.
As I already said, I'd really appreciate it if you could handle the indexedDB stuff. Also I absolutely do not mind if you delay merging this PR until that is addressed.

2024-05-20 14:36 UTC, lmg-anon commented
>As I already said, I'd really appreciate it if you could handle the indexedDB stuff. Also I absolutely do not mind if you delay merging this PR until that is addressed.

No problem. I will try to handle it and commit to your branch before merging the PR.

2024-05-20 18:40 UTC, lmg-anon commented
Alright, I think this is it. If possible, I would like you to take a second look to see if you find anything wrong, but this should be fine to merge now.

2024-05-20 19:21 UTC, neCo2 commented
Imports weren't working as templateStorage wasn't an argument for `App()` and the function still used `sessionStorage.saveTemplates`, but that's the only issue I found.

2024-05-20 20:51 UTC, lmg-anon commented
Great, thanks for another great contribution!

2024-05-20 20:51 UTC, merged

2024-05-21 08:33 UTC, neCo2 commented
Thank you for polishing it up!